import { useRef, useState } from "react"

export default function Tips({ setListsPage }) {

   const qr_code = useRef()
   const timeout = useRef(null)
   const [msgHidden, setMsgHidden] = useState(true)

   const copy_qr_code = () => {

      navigator.clipboard.writeText(qr_code.current.innerText)
      setMsgHidden(false)

      if (timeout.current)
      {
         clearTimeout(timeout.current)
      }

      timeout.current = setTimeout(() => {
         setMsgHidden(true)
      }, 1500)
   }

   return (
      <section className="tips">
         <button type="button" onClick={() => setListsPage(true)}>Go Back</button>
         <ol>
            <li>If you want NarrowD to use a different search engine, change your
               browser's search engine (in your browser settings).</li>
            <li>If your search throws no results, try removing the quotation marks from the text generated by NarrowD (in the results page).</li>
            <li><kbd>Ctrl+Shift+Space</kbd> opens NarrowD's popup.</li>
            <li><kbd>Ctrl+Space</kbd> focuses the current site's search bar (if any) so you can type in it right away (it doesn't work on every site, though).</li>
            <li>Some search engines have a 32-word limit. A "word" is any character sequence delimited by whitespace, for example: "this.counts-as-one.word", so the number of words in your query plus the number of check-marked sites of your active list should not exceed 32, or the search engine might ignore some of the query.</li>
         </ol>
         <img src="./icons/QR_BTC.jpeg" alt="Bitcoin_Quick_Response_code" />
         <button type="button" name="copy_qr_btn" onClick={copy_qr_code} title="Copy QR Code">
            <span ref={qr_code}>3DgeHYTfif7Neg5eLVTNgxEPd2gSbq2Pzq</span>
            <span className="feedback" hidden={msgHidden}>Copied!</span>
         </button>
      </section>
   )
}